---
version: '2'

services:

  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    command: start.sh jupyter lab --LabApp.token='${JUPYTER_TOKEN}'  --LabApp.allow_remote_access='True' --LabApp.allow_origin='*'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ${JUPYTER_HOME}:/home/jovyan
    hostname: jupyter

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl.pem:/etc/nginx/ssl.pem
      - ./ssl.key:/etc/nginx/ssl.key
      - ./nginx.conf:/etc/nginx/nginx.conf

